echo off

goto:begin

:CreateProjBegin
echo ^<^?xml version="1.0" encoding="utf-8"^?^> >"test.vcxproj"
echo ^<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003"^> >>"test.vcxproj"
echo   ^<ItemGroup Label="ProjectConfigurations"^> >>"test.vcxproj"
echo     ^<ProjectConfiguration Include="Debug|Win32"^> >>"test.vcxproj"
echo       ^<Configuration^>Debug^</Configuration^> >>"test.vcxproj"
echo       ^<Platform^>Win32^</Platform^> >>"test.vcxproj"
echo     ^</ProjectConfiguration^> >>"test.vcxproj"
echo     ^<ProjectConfiguration Include="Release|Win32"^> >>"test.vcxproj"
echo       ^<Configuration^>Release^</Configuration^> >>"test.vcxproj"
echo       ^<Platform^>Win32^</Platform^> >>"test.vcxproj"
echo     ^</ProjectConfiguration^> >>"test.vcxproj"
echo     ^<ProjectConfiguration Include="Debug|x64"^> >>"test.vcxproj"
echo       ^<Configuration^>Debug^</Configuration^> >>"test.vcxproj"
echo       ^<Platform^>x64^</Platform^> >>"test.vcxproj"
echo     ^</ProjectConfiguration^> >>"test.vcxproj"
echo     ^<ProjectConfiguration Include="Release|x64"^> >>"test.vcxproj"
echo       ^<Configuration^>Release^</Configuration^> >>"test.vcxproj"
echo       ^<Platform^>x64^</Platform^> >>"test.vcxproj"
echo     ^</ProjectConfiguration^> >>"test.vcxproj"
echo   ^</ItemGroup^> >>"test.vcxproj"
echo   ^<PropertyGroup Label="Globals"^> >>"test.vcxproj"
echo     ^<VCProjectVersion^>16.0^</VCProjectVersion^> >>"test.vcxproj"
echo     ^<ProjectGuid^>{198C1B67-8716-494B-8698-3E90AB38B3E3}^</ProjectGuid^> >>"test.vcxproj"
echo     ^<Keyword^>Win32Proj^</Keyword^> >>"test.vcxproj"
echo   ^</PropertyGroup^> >>"test.vcxproj"
echo   ^<Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" /^> >>"test.vcxproj"
echo   ^<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration"^> >>"test.vcxproj"
echo     ^<ConfigurationType^>Application^</ConfigurationType^> >>"test.vcxproj"
echo     ^<UseDebugLibraries^>true^</UseDebugLibraries^> >>"test.vcxproj"
echo     ^<PlatformToolset^>v142^</PlatformToolset^> >>"test.vcxproj"
echo   ^</PropertyGroup^> >>"test.vcxproj"
echo   ^<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'" Label="Configuration"^> >>"test.vcxproj"
echo     ^<ConfigurationType^>Application^</ConfigurationType^> >>"test.vcxproj"
echo     ^<UseDebugLibraries^>false^</UseDebugLibraries^> >>"test.vcxproj"
echo     ^<PlatformToolset^>v142^</PlatformToolset^> >>"test.vcxproj"
echo   ^</PropertyGroup^> >>"test.vcxproj"
echo   ^<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration"^> >>"test.vcxproj"
echo     ^<ConfigurationType^>Application^</ConfigurationType^> >>"test.vcxproj"
echo     ^<UseDebugLibraries^>true^</UseDebugLibraries^> >>"test.vcxproj"
echo     ^<PlatformToolset^>v142^</PlatformToolset^> >>"test.vcxproj"
echo   ^</PropertyGroup^> >>"test.vcxproj"
echo   ^<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration"^> >>"test.vcxproj"
echo     ^<ConfigurationType^>Application^</ConfigurationType^> >>"test.vcxproj"
echo     ^<UseDebugLibraries^>false^</UseDebugLibraries^> >>"test.vcxproj"
echo     ^<PlatformToolset^>v142^</PlatformToolset^> >>"test.vcxproj"
echo   ^</PropertyGroup^> >>"test.vcxproj"
echo   ^<Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" /^> >>"test.vcxproj"
echo   ^<ImportGroup Label="ExtensionSettings"^> >>"test.vcxproj"
echo   ^</ImportGroup^> >>"test.vcxproj"
echo   ^<ImportGroup Label="Shared"^> >>"test.vcxproj"
echo   ^</ImportGroup^> >>"test.vcxproj"
echo   ^<ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'"^> >>"test.vcxproj"
echo     ^<Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" /^> >>"test.vcxproj"
echo   ^</ImportGroup^> >>"test.vcxproj"
echo   ^<ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|Win32'"^> >>"test.vcxproj"
echo     ^<Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" /^> >>"test.vcxproj"
echo   ^</ImportGroup^> >>"test.vcxproj"
echo   ^<ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'"^> >>"test.vcxproj"
echo     ^<Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" /^> >>"test.vcxproj"
echo   ^</ImportGroup^> >>"test.vcxproj"
echo   ^<ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|x64'"^> >>"test.vcxproj"
echo     ^<Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" /^> >>"test.vcxproj"
echo   ^</ImportGroup^> >>"test.vcxproj"
echo   ^<PropertyGroup Label="UserMacros" /^> >>"test.vcxproj"
echo   ^<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'"^> >>"test.vcxproj"
echo     ^<LinkIncremental^>true^</LinkIncremental^> >>"test.vcxproj"
echo   ^</PropertyGroup^> >>"test.vcxproj"
echo   ^<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'"^> >>"test.vcxproj"
echo     ^<LinkIncremental^>true^</LinkIncremental^> >>"test.vcxproj"
echo   ^</PropertyGroup^> >>"test.vcxproj"
echo   ^<ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'"^> >>"test.vcxproj"
echo     ^<ClCompile^> >>"test.vcxproj"
echo       ^<PreprocessorDefinitions^>WIN32;_DEBUG;_CONSOLE;%%(PreprocessorDefinitions)^</PreprocessorDefinitions^> >>"test.vcxproj"
echo       ^<RuntimeLibrary^>MultiThreadedDebugDLL^</RuntimeLibrary^> >>"test.vcxproj"
echo       ^<WarningLevel^>Level3^</WarningLevel^> >>"test.vcxproj"
echo       ^<DebugInformationFormat^>ProgramDatabase^</DebugInformationFormat^> >>"test.vcxproj"
echo       ^<Optimization^>Disabled^</Optimization^> >>"test.vcxproj"
echo     ^</ClCompile^> >>"test.vcxproj"
echo     ^<Link^> >>"test.vcxproj"
echo       ^<TargetMachine^>MachineX86^</TargetMachine^> >>"test.vcxproj"
echo       ^<GenerateDebugInformation^>true^</GenerateDebugInformation^> >>"test.vcxproj"
echo       ^<SubSystem^>Console^</SubSystem^> >>"test.vcxproj"
echo     ^</Link^> >>"test.vcxproj"
echo   ^</ItemDefinitionGroup^> >>"test.vcxproj"
echo   ^<ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'"^> >>"test.vcxproj"
echo     ^<ClCompile^> >>"test.vcxproj"
echo       ^<PreprocessorDefinitions^>WIN32;NDEBUG;_CONSOLE;%%(PreprocessorDefinitions)^</PreprocessorDefinitions^> >>"test.vcxproj"
echo       ^<RuntimeLibrary^>MultiThreadedDLL^</RuntimeLibrary^> >>"test.vcxproj"
echo       ^<WarningLevel^>Level3^</WarningLevel^> >>"test.vcxproj"
echo       ^<DebugInformationFormat^>ProgramDatabase^</DebugInformationFormat^> >>"test.vcxproj"
echo     ^</ClCompile^> >>"test.vcxproj"
echo     ^<Link^> >>"test.vcxproj"
echo       ^<TargetMachine^>MachineX86^</TargetMachine^> >>"test.vcxproj"
echo       ^<GenerateDebugInformation^>true^</GenerateDebugInformation^> >>"test.vcxproj"
echo       ^<SubSystem^>Console^</SubSystem^> >>"test.vcxproj"
echo       ^<EnableCOMDATFolding^>true^</EnableCOMDATFolding^> >>"test.vcxproj"
echo       ^<OptimizeReferences^>true^</OptimizeReferences^> >>"test.vcxproj"
echo     ^</Link^> >>"test.vcxproj"
echo   ^</ItemDefinitionGroup^> >>"test.vcxproj"
echo   ^<ItemGroup^> >>"test.vcxproj"
goto:eof

:FinishProjFile
echo   ^</ItemGroup^> >>"test.vcxproj"
echo   ^<Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" /^> >>"test.vcxproj"
echo   ^<ImportGroup Label="ExtensionTargets"^> >>"test.vcxproj"
echo   ^</ImportGroup^> >>"test.vcxproj"
echo ^</Project^> >>"test.vcxproj"
goto:eof

:treeProcess
for /d %%i in (*) do (
  cd %%i
  call:CreateProjBegin
  for %%j in (*.cpp) do echo     ^<ClCompile Include="%%j" /^> >>"test.vcxproj"
  echo   ^</ItemGroup^> >>"test.vcxproj"
  echo   ^<ItemGroup^> >>"test.vcxproj"
  for %%j in (*.h) do echo     ^<ClInclude Include="%%j" /^> >>"test.vcxproj"
  call:FinishProjFile
  call:treeProcess
  cd ..
)
goto:eof


:begin
call:treeProcess